In [2]:
import numpy as np

In [5]:
recipes= np.genfromtxt("recipes.csv", delimiter =",")
print(recipes)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


In [6]:
eggs= recipes[:,2]
print(eggs)

[2. 1. 1. 2.]


In [7]:
eggs== 1

array([False,  True,  True, False])

In [9]:
cupcakes=recipes[0,:]
cookies= recipes[2,:]
print(cupcakes)
print(cookies)

[2.   0.75 2.   1.   0.5 ]
[2.75 1.5  1.   0.   1.  ]


In [10]:
grocery_list=2*cupcakes+cookies
print(grocery_list)

[6.75 3.   5.   2.   2.  ]
